version: '3.7'

services:
  nginx:
    build: ./services/nginx
    image: barnabyrh/psolb 
    ports:
      - target: 80
        published: 80
    depends_on:
      - frontend

  frontend:
    build: ./services/python/front_end
    image: barnabyrh/frontend
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - FIG_IP=localhost
    depends_on:
      - graphing

  graphing:
    build: ./services/python/graphing_service
    image: barnabyrh/graphing
    depends_on:
      - party

  logic:
    build: ./services/python/logic
    image: barnabyrh/logic
    environment:
      - DATABASE_URI=${DATABASE_URI}
    depends_on:
      - psodb

  party:
    build: ./services/python/particle_service
    image: barnabyrh/party
    environment:
      - DATABASE_URI=${DATABASE_URI}
    depends_on:
      - psodb
      - logic

  psodb:
    build: ./services/mysql
    image: barnabyrh/psodb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}